[build]
  publish = "out"
  command = "npm run netlify-build"

[build.environment]
  NODE_VERSION = "18"
  DEMO_MODE = "true"

# Add Netlify Functions configuration
[functions]
  directory = "netlify/functions"

# Redirect /api calls to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback for any missing routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  DEMO_MODE = "false"

[context.deploy-preview.environment]  
  DEMO_MODE = "true"

[context.branch-deploy.environment]
  DEMO_MODE = "true"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000" 

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 